#!/bin/bash
set -aeo pipefail

handle_sig(){
  systemd-notify --status "Exiting" \
    && sleep 3 \
    && exit 0
}

trap handle_sig SIGHUP SIGINT SIGQUIT

[[ -z "${QREXEC_REMOTE_DOMAIN}" && -z "${LISTEN_FDS}" ]] \
  && echo "No remote to work with" \
  && exit 1


notify-send --ready --status "Root socket ready"


systemctl --user start "onlykey-agent-daemon-factory@$(systemd-escape "${QREXEC_REMOTE_DOMAIN}").socket"

# TODO: wtf do i do here?
socat fd:

