#!/bin/bash
set -aeo pipefail
set -x

log() {
	systemd-cat --identifier="onlykey-agent-socket" echo "${@}"
}

handle_sig(){
  systemd-notify --status "Exiting" \
    && sleep 3 \
    && exit 0
}

trap handle_sig SIGHUP SIGINT SIGQUIT

[[ -z "${QREXEC_REMOTE_DOMAIN}" && -z "${LISTEN_FDS}" ]] \
  && echo "No remote to work with" \
  && exit 1

get_daemon_service() {
  systemctl show --user --property=Listen "onlykey-agent-daemon@${QREXEC_REMOTE_DOMAIN}"
}

echo -n "${QREXEC_REMOTE_DOMAIN}" | nc -U "${XDG_RUNTIME_DIR}/onlykey-agent/daemon-factory.sock"

SSH_AUTH_SOCK=$(get_daemon_service | grep -o "/run.*" | cut -d\  -f 1)
export SSH_AUTH_SOCK

notify-send --ready --status "Root socket ready"
socat - "unix-connect:${SSH_AUTH_SOCK:-"${XDG_RUNTIME_DIR}/onlykey-agent/S.ssh-agent"},fork,unlink-early"


