#!/bin/bash
set -aeo pipefail
set -x
identifier="${0}"

env

log() {
  systemd-cat --identifier="${identifier}" echo "${@}"
}

handle_sig(){
  systemd-notify --status "Exiting" \
    && sleep 3 \
    && exit 0
}


trap handle_sig SIGHUP SIGINT SIGQUIT

[[ -z "${OK_CLIENT_DOMAIN}" ]] \
  && echo "No client domain specified, exiting" \
  && exit 1



busctl call \
  org.freedesktop.systemd1 \
  /org/freedesktop/systemd1 \
  org.freedesktop.systemd1.Manager \
  StartUnit \
  ss \
  "onlykey-agent-daemon-factory@${OK_CLIENT_DOMAIN}.service" \
  replace

