#!/bin/bash
set -aeo pipefail

handle_sig(){
  systemd-notify --status "Exiting" \
    && sleep 3 \
    && exit 0  
}

trap handle_sig SIGHINT

[[ -z "${QREXEC_REMOTE_DOMAIN}" && -z "${LISTEN_FDS}" ]] \
  && echo "No remote to work with" \
  && exit 1


systemd-notify --ready --status "Root socket ready"
  
# TODO: configure a default


systemctl --user start onlykey-agent-daemon@$(systemd-escape "${QREXEC_REMOTE_DOMAIN}").socket
systemd-notify --status "Started a daemon for ${QREXEC_REMOTE_DOMAIN}"

exit 0
