#!/bin/bash --
set -aeo pipefail
set -x

validate_qrexec_target() {
  if [[ ! "${1}" =~ ^[A-Za-z@][:0-9A-Za-z_-]+$ ]]; then
    printf 'Qrexec target (%q) is invalid\n' "${1}" >&2
    exit 1
  fi
}

identity="${1:-$SSH_IDENTITY}"

[[ -n "${identity}" ]] \
  && ssh_identity_qrexec_arg="+${identity}" \
  || ssh_identity_qrexec_arg=""

validate_qrexec_target "${QUBES_ONLYKEY_DOMAIN}"

# qrexec-client-vm "${QUBES_ONLYKEY_DOMAIN}" "onlykey.SshAgent${ssh_identity_qrexec_arg}" &

umask 177 && exec socat
  "unix-listen:'${OK_SSH_SOCK}',fork,unlink-early"
  "exec:qrexec-client-vm ${QUBES_ONLYKEY_DOMAIN} onlykey.SshAgent${ssh_identity_qrexec_arg}"
